name: Scan Vuln
on: [push,workflow_dispatch]
permissions: 
  security-events: write
jobs:
  Code-Scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action@fix/broken-testing
        with:
          skip-upload: false
          go-version: 1.18
        env:
          DEBUG: "true"
          GH_PAT_TOKEN: ${{ secrets.GH_ACCESS }}
          GOPRIVATE: "github.com/Templum/private-lib"
      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: raw-report
          path: raw-report.json
